name: Push-to-EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v3.0.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-44-220-134-91.compute-1.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu"
